# Generated by Django 5.2 on 2025-07-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default='Unnamed Resume', max_length=100),
            preserve_default=False,
        ),
    ]
