# Generated by Django 5.2 on 2025-07-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
